### ISSUE TITLE
TypeError: unrecognized operator 'ATen'

### ISSUE THREAD

**Issue by aletulier** [Microsoft/onnxjs#80]
When trying to use a unet model exported from pytorch 1.0 I get the following error:
TypeError: unrecognized operator 'ATen'
    at createOperator (/home/alexis/devs/javainference/node_modules/onnxjs/lib/backends/cpu/ops-resolve.js:157:19)
    at Object.resolve (/home/alexis/devs/javainference/node_modules/onnxjs/lib/backends/cpu/ops-resolve.js:35:14)
    at WasmSessionHandler.createOperator (/home/alexis/devs/javainference/node_modules/onnxjs/lib/backends/wasm/session-handler.js:51:42)
    at WasmSessionHandler.resolve (/home/alexis/devs/javainference/node_modules/onnxjs/lib/backends/wasm/session-handler.js:24:23)
    at Session.initializeOps (/home/alexis/devs/javainference/node_modules/onnxjs/lib/session.js:261:48)
    at /home/alexis/devs/javainference/node_modules/onnxjs/lib/session.js:125:19
    at Profiler.event (/home/alexis/devs/javainference/node_modules/onnxjs/lib/instrument.js:200:25)
    at Session.initialize (/home/alexis/devs/javainference/node_modules/onnxjs/lib/session.js:116:23)
    at Session.<anonymous> (/home/alexis/devs/javainference/node_modules/onnxjs/lib/session.js:79:46)
    at step (/home/alexis/devs/javainference/node_modules/onnxjs/lib/session.js:34:23)

I guess this is because the onnx.js library doesn't yet support this operator.

**Comment by aletulier** [comment]
Indeed, it seems to be the case, the operations here that is not support is _weight_norm

**Comment by NTT123** [comment]
Sorry I missed it. 

So, you can use `remove_weight_norm` from here https://pytorch.org/docs/stable/nn.html?highlight=weight_norm#torch.nn.utils.remove_weight_norm to remove the `weight_norm` ops. This is OK because `weight_norm` is useful for training only. We can remove it and restore to the original linear function when doing evaluation.

**Comment by aletulier** [comment]
Thank you very much,
It did the trick for weight_norm. Now, time for inference !

**Comment by fs-eire** [comment]
`ATen` is a special operator. It's designed to be a fallback for pytorch and its behavior is left to pytorch's implementation. It is going to be removed in the latest ONNX spec (opset v10).

This operator is not going to be supported in future.
